[workspace]
resolver = "2"
members = ["crates/vbt", "crates/rss"]
# Main
default-members = ["crates/vbt"]

[workspace.dependencies]
dotenv = "0.15.0"
rss = {path = "crates/rss"}

[profile.release]
debug = false
lto = "thin"
opt-level = 2
panic = 'abort'
