name: Daily Run

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Run
        run: cargo run
        env:
          DAILY: ${{ secrets.DAILY }}
          PROCESSED: ${{ secrets.PROCESSED }}

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update feed data [skip ci]"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          status_options: "--untracked-files=no"
